### ISSUE TITLE
Error message "Failed to compile" after clicking the link "http://localhost:3000/"

### ISSUE THREAD

**Issue by WuHaohui1231** [CVWO/sample-react-app#3]
I followed the guide to run the app. But when I clicked the "http://localhost:3000/" link, it displayed the expected page for just a flash and then threw an error message like this. I tried deleting ".prettierrc.js" file but it acted exactly the same. Could anyone help?
<img width="630" alt="Issue" src="https://user-images.githubusercontent.com/95847459/147478540-6c9ad069-0681-4c9c-bd48-b376acaf0ac4.png">

**Comment by zognin** [comment]
@WuHaohui1231 could you run `yarn format:fix` and see if that fixes the endOfLine to `lf` only? You can look up [newline (or end of line) codes](https://www.pcmag.com/encyclopedia/term/line-break) for a better understanding.

**Comment by WuHaohui1231** [comment]
It worked. tks
